#!/usr/bin/env bash
# Pre-deploy gate — ensure every repo is committed, pushed, and version-tagged before `azd` deploy.
# Generated by enterprise-copilot-fleet-controller for word-game.
set -euo pipefail

info() { printf '[gate] %s\n' "$*"; }
warn() { printf '[gate][warn] %s\n' "$*" >&2; }
die()  { printf '[gate][error] %s\n' "$*" >&2; exit 1; }

HARNESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_INDEX="$HARNESS_DIR/.repo-index.yml"
COMMIT_MSG="${1:-chore(deploy): pre-deploy gate commit}"

command -v git >/dev/null 2>&1 || die "git is required"

# Collect repo dirs: the harness itself + each child local_path from .repo-index.yml.
declare -a REPOS=("$HARNESS_DIR")
if [[ -f "$REPO_INDEX" ]]; then
  while IFS= read -r p; do
    [[ -n "$p" ]] || continue
    case "$p" in
      /*) rp="$p" ;;
      *)  rp="$(cd "$HARNESS_DIR/$p" 2>/dev/null && pwd || true)" ;;
    esac
    [[ -n "$rp" && -d "$rp/.git" ]] && REPOS+=("$rp")
  done < <(grep -E '^\s*local_path:' "$REPO_INDEX" | sed -E 's/^\s*local_path:\s*"?([^"]+)"?\s*$/\1/')
fi

next_tag() {
  # Compute next patch version tag (vMAJOR.MINOR.PATCH) for a repo.
  local latest
  latest="$(git tag --list 'v*' --sort=-v:refname | head -n1)"
  [[ -z "$latest" ]] && { echo "v0.1.0"; return; }
  local ver="${latest#v}"
  local major="${ver%%.*}"; local rest="${ver#*.}"
  local minor="${rest%%.*}"; local patch="${rest#*.}"
  [[ "$patch" =~ ^[0-9]+$ ]] || patch=0
  echo "v${major}.${minor}.$((patch + 1))"
}

failed=0
for repo in "${REPOS[@]}"; do
  info "Gating $repo"
  pushd "$repo" >/dev/null

  # 1. Commit any pending changes.
  if [[ -n "$(git status --porcelain)" ]]; then
    git add -A
    git commit -m "$COMMIT_MSG" || warn "nothing to commit in $repo"
  else
    info "working tree clean"
  fi

  # 2. Push to the current branch's upstream (or origin/<branch>).
  branch="$(git rev-parse --abbrev-ref HEAD)"
  if git remote get-url origin >/dev/null 2>&1; then
    git push origin "HEAD:$branch" || { warn "push failed for $repo"; failed=1; }
  else
    warn "no origin remote in $repo — skipping push"
  fi

  # 3. Version tag (idempotent: skip if HEAD already tagged).
  if [[ -z "$(git tag --points-at HEAD)" ]]; then
    tag="$(next_tag)"
    git tag -a "$tag" -m "release $tag" && info "tagged $tag"
    git remote get-url origin >/dev/null 2>&1 && { git push origin "$tag" || { warn "tag push failed for $repo"; failed=1; }; }
  else
    info "HEAD already tagged: $(git tag --points-at HEAD | tr '\n' ' ')"
  fi

  popd >/dev/null
done

[[ "$failed" -eq 0 ]] || die "Pre-deploy gate failed for one or more repos — resolve before deploying."
info "Pre-deploy gate PASSED — all repos committed, pushed, and tagged. Safe to run azd."
